GRD: bump since build for 213 builds
It should prevent `java.lang.NoClassDefFoundError: com/intellij/application/options/IndentOptionsEditorBase` after fix of [IDEA-281472](https://youtrack.jetbrains.com/issue/IDEA-281472)

(cherry picked from commit af9156d61020f1a0e9538441d9df477b4a41048b)