Move `TestUnitTestRustcCacheService` into main source set
Otherwise, it won't be included into plugin artifact that will lead to `NoClassDefFoundError` during test running in any other plugin that depends on Rust plugin (for example, EduTools plugin)