GRAM: Support the new '..=' syntax for inclusive ranges
Inclusive ranges are currently a unstable feature of Rust.
'..=' for ranges requires #![feature(inclusive_range_syntax)]
'..=' for range patterns requires #![feature(dotdoteq_in_patterns)]

The nightly version of Rust does not accept the previous syntax
'...' for inclusive ranges anymore.
(For range patterns the old syntax is still supported)

It produces the following output:
error: `...` syntax cannot be used in expressions
help: Use `..` if you need an exclusive range (a < b)
help: or `..=` if you need an inclusive range (a <= b)

We still support the old '...' syntax for both ranges and range patterns.

See the tracking issue rust-lang/rust/issues/28237 for '..=' inclusive
ranges. (RFC 1192)

Fixes #2335

(cherry picked from commit 6f84a9c)