GRD: update `org.jetbrains.grammarkit` to `2021.2.2`
It should fix `java.lang.NoClassDefFoundError: com/intellij/openapi/util/SystemInfoRt` during parser generation.
Also, drop hack with `bomConfiguration` because it was deleted from the plugin