GRD: temporarily disable `buildSearchableOptions` task for 212 platform
It fails because of `NoClassDefFoundError`

(cherry picked from commit 56ad131fccc5a06709a0034cde7a1b0e1e109667)